openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
  description: Library API
tags:
  - name: Service Api Client
    description: Service Api Client
servers:
  - url: /clients
paths:
  /{id}:
    get:
      tags:
        - Client
      summary: Get client by id
      description: Get client by id
      parameters:
        - name: id
          in: path
          description: Client id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        "400":
          description: Request is not correct.
        "404":
          description: There is no endpoint found.
        "500":
          description: Internal Server Error.
  /list:
    get:
      tags:
        - Clients Service
      summary: Get all clients
      description: Get all clients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        "400":
          description: Request is not correct.
        "404":
          description: There is no endpoint found.
        "500":
          description: Internal Server Error.
  /register:
    post:
      tags:
        - Clients Service
      summary: Create new client
      description: Create new client
      requestBody:
        description: Client
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        "400":
          description: Request is not correct.
        "404":
          description: There is no endpoint found.
        "500":
          description: Internal Server Error.
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        clientIdentityType:
          type: string
        clientIdentityNumber:
          type: string
        clientType:
          type: string
